//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chatter
    {
        public int ChatterID { get; set; }
        public string ChatMsg { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string UserNameID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
